version: 1
aliases:
  reporter: 
    - "Country"
    - "COUNTRY"
    - "COUNTRY.NAME"
    - "Reporter"
    - "REPORTER"
    - "REF_AREA"
    - "REF_AREA.NAME"
  partner: 
    - "Counterpart Country"
    - "COUNTERPART_COUNTRY"
    - "COUNTERPART_COUNTRY.NAME"
    - "Partner"
    - "PARTNER"
    - "COUNTERPART_AREA"
  indicator: 
    - "INDICATOR"
    - "INDICATOR.ID"
    - "Indicator"
    - "SERIES"
    - "Series"
  scale_id: 
    - "SCALE.ID"
    - "SCALE"
    - "Scale"
    - "SCALE_CODE"
