"""Render FINAL_RECORD.md using GCS-validated pointers and local headline stats."""
import ast
import subprocess
from pathlib import Path


def sh(cmd: list[str]) -> str:
    import platform
    if platform.system() == "Windows" and cmd[0] == "gcloud":
        cmd[0] = "gcloud.cmd"
    return subprocess.check_output(cmd, text=True, stderr=subprocess.STDOUT)


def exists(uri: str) -> bool:
    try:
        sh(["gcloud", "storage", "ls", uri])
        return True
    except Exception:
        return False


def main():
    bucket = "gs://pathograph-057a2273fe-data"
    phase3_agg = f"{bucket}/runs/stepA/phase3/_aggregate"
    phase3_reports = f"{bucket}/runs/stepA/phase3/_reports"

    champion = {
        "package": f"{bucket}/packages/pathograph_adaptive_calib_20260221.tar.gz",
        "config": f"{bucket}/configs/stmm_stepA_adaptive.yaml",
        "best_ckpt": f"{bucket}/runs/stepA/phase2/adaptive_s1338/epoch=8-step=7128-val_auroc_macro=0.9771.ckpt",
        "phase2_run_prefix": f"{bucket}/runs/stepA/phase2/adaptive_s1338",
    }

    # Load headline stats from pull_phase3_aggregate.py output
    stats_path = Path("reports/phase3/_local_cache/headline_stats.txt")
    stats = {}
    if stats_path.exists():
        try:
            stats = ast.literal_eval(stats_path.read_text(encoding="utf-8"))
        except Exception:
            stats = {}

    def fmt_metric(name: str) -> str:
        v = stats.get(name)
        if not v:
            return f"- `{name}`: TODO (not found in aggregate CSV)"
        return (
            f"- `{name}`: mean={v.get('mean'):.4f}  "
            f"std={v.get('std'):.4f}  "
            f"min={v.get('min'):.4f}  "
            f"max={v.get('max'):.4f}"
        )

    lines = []
    lines.append("# FINAL_RECORD — Step A\n\n")
    lines.append("> Auto-generated by `tools/reporting/render_final_record.py`. "
                 "GCS URIs validated at write time.\n\n")

    lines.append("## Repo Health\n\n")
    lines.append("- Data staging: `tools/stage_stepA_v1_from_gcs.ps1`\n")
    lines.append("- Pytest gate: `python -m pytest -q` → expected pass/skip, no failures\n")
    lines.append("- Package build: `python -m build --sdist`\n\n")

    lines.append("## Freeze Record (Adaptive Champion)\n\n")
    for k, uri in champion.items():
        ok = exists(uri)
        tag = "✅ OK" if ok else "❌ TODO_NOT_FOUND"
        lines.append(f"- **{k}**: `{uri}` — {tag}\n")
    lines.append("\n")

    lines.append("## Phase 3 Aggregate (GCS)\n\n")
    agg_ok = exists(phase3_agg)
    rep_ok = exists(phase3_reports)
    lines.append(f"- Aggregate prefix: `{phase3_agg}` — {'✅ OK' if agg_ok else '❌ TODO_NOT_FOUND'}\n")
    lines.append(f"- Reports prefix:   `{phase3_reports}` — {'✅ OK' if rep_ok else '❌ TODO_NOT_FOUND'}\n\n")

    lines.append("### Headline Test Metrics (Phase 3 Calibrated Summary)\n\n")
    for m in ["test_auroc_macro", "test_auprc_macro", "test_brier_macro", "test_ece_macro"]:
        lines.append(fmt_metric(m) + "\n")
    lines.append("\n")

    lines.append("## Notes\n\n")
    lines.append("- GCS is the source of truth. Do not commit Zarr stores, run dirs, or report images.\n")
    lines.append("- See `VERTEX_JOB_MATRIX.md` for Vertex job args.\n")
    lines.append("- See `RUN_INSTRUCTIONS_ALL_FAMILIES.md` for local + Vertex run workflow.\n")

    Path("FINAL_RECORD.md").write_text("".join(lines), encoding="utf-8")
    print("WROTE FINAL_RECORD.md")


if __name__ == "__main__":
    main()
